name: build
on:
  push:
    branches:
      - main

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker repository
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURECR_URL }}
          username: ${{ secrets.AZURECR_USER }}
          password: ${{ secrets.AZURECR_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.AZURECR_URL }}/docker-dind-azcli:latest
